/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuestImport } from './routes/_guest'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTeamImport } from './routes/_authenticated/dashboard/team'
import { Route as AuthenticatedDashboardProjectsImport } from './routes/_authenticated/dashboard/projects'

// Create Virtual Routes

const GuestAuthRegisterLazyImport = createFileRoute('/_guest/auth/register')()
const GuestAuthLoginLazyImport = createFileRoute('/_guest/auth/login')()

// Create/Update Routes

const GuestRoute = GuestImport.update({
  id: '/_guest',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const GuestAuthRegisterLazyRoute = GuestAuthRegisterLazyImport.update({
  path: '/auth/register',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/auth/register.lazy').then((d) => d.Route),
)

const GuestAuthLoginLazyRoute = GuestAuthLoginLazyImport.update({
  path: '/auth/login',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/auth/login.lazy').then((d) => d.Route),
)

const AuthenticatedDashboardTeamRoute = AuthenticatedDashboardTeamImport.update(
  {
    path: '/dashboard/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsImport.update({
    path: '/dashboard/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/team': {
      id: '/_authenticated/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AuthenticatedDashboardTeamImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_guest/auth/login': {
      id: '/_guest/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginLazyImport
      parentRoute: typeof GuestImport
    }
    '/_guest/auth/register': {
      id: '/_guest/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof GuestAuthRegisterLazyImport
      parentRoute: typeof GuestImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedDashboardProjectsRoute,
    AuthenticatedDashboardTeamRoute,
    AuthenticatedDashboardIndexRoute,
  }),
  GuestRoute: GuestRoute.addChildren({
    GuestAuthLoginLazyRoute,
    GuestAuthRegisterLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_guest"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.ts",
      "children": [
        "/_authenticated/dashboard/projects",
        "/_authenticated/dashboard/team",
        "/_authenticated/dashboard/"
      ]
    },
    "/_guest": {
      "filePath": "_guest.ts",
      "children": [
        "/_guest/auth/login",
        "/_guest/auth/register"
      ]
    },
    "/_authenticated/dashboard/projects": {
      "filePath": "_authenticated/dashboard/projects.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/team": {
      "filePath": "_authenticated/dashboard/team.tsx",
      "parent": "/_authenticated"
    },
    "/_guest/auth/login": {
      "filePath": "_guest/auth/login.lazy.tsx",
      "parent": "/_guest"
    },
    "/_guest/auth/register": {
      "filePath": "_guest/auth/register.lazy.tsx",
      "parent": "/_guest"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
